//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW2PDT5
{
    using System;
    using System.Collections.Generic;
    
    public partial class compra
    {
        public compra()
        {
            this.compra_proveedor = new HashSet<compra_proveedor>();
            this.deta_compra = new HashSet<deta_compra>();
        }
    
        public int id_compra { get; set; }
        public int PRODUCTO_id_producto { get; set; }
        public int NOTA_CREDITO_id_nora_credito { get; set; }
        public int USUARIO_id_usuario { get; set; }
        public int cantidad_compra { get; set; }
        public int ORDEN_COMPRA_id_orden_compra { get; set; }
    
        public virtual nota_credito nota_credito { get; set; }
        public virtual orden_compra orden_compra { get; set; }
        public virtual producto producto { get; set; }
        public virtual ICollection<compra_proveedor> compra_proveedor { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual ICollection<deta_compra> deta_compra { get; set; }
    }
}
