//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW2PDT5
{
    using System;
    using System.Collections.Generic;
    
    public partial class deta_compra
    {
        public int id_deta_compra { get; set; }
        public int COMPRA_id_compra { get; set; }
    
        public virtual compra compra { get; set; }
    }
}
