//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW2PDT5
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class mydbEntities : DbContext
    {
        public mydbEntities()
            : base("name=mydbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<caja> cajas { get; set; }
        public DbSet<categoria_producto> categoria_producto { get; set; }
        public DbSet<compra> compras { get; set; }
        public DbSet<compra_proveedor> compra_proveedor { get; set; }
        public DbSet<departamento> departamentoes { get; set; }
        public DbSet<deta_compra> deta_compra { get; set; }
        public DbSet<detalle_venta> detalle_venta { get; set; }
        public DbSet<empleado> empleadoes { get; set; }
        public DbSet<municipio> municipios { get; set; }
        public DbSet<nota_credito> nota_credito { get; set; }
        public DbSet<orden_compra> orden_compra { get; set; }
        public DbSet<persona> personas { get; set; }
        public DbSet<presentacion_producto> presentacion_producto { get; set; }
        public DbSet<producto> productoes { get; set; }
        public DbSet<producto_sucursal> producto_sucursal { get; set; }
        public DbSet<proveedor> proveedors { get; set; }
        public DbSet<rol> rols { get; set; }
        public DbSet<seccion_bodega> seccion_bodega { get; set; }
        public DbSet<sucursal> sucursals { get; set; }
        public DbSet<tipo_nota_credito> tipo_nota_credito { get; set; }
        public DbSet<tipo_proveedor> tipo_proveedor { get; set; }
        public DbSet<tipo_venta> tipo_venta { get; set; }
        public DbSet<usuario> usuarios { get; set; }
        public DbSet<venta> ventas { get; set; }
        public DbSet<venta_producto> venta_producto { get; set; }
    }
}
