//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW2PDT5
{
    using System;
    using System.Collections.Generic;
    
    public partial class municipio
    {
        public municipio()
        {
            this.personas = new HashSet<persona>();
            this.sucursals = new HashSet<sucursal>();
        }
    
        public int id_municipio { get; set; }
        public string mun_nom { get; set; }
        public int DEPARTAMENTO_id_departamento { get; set; }
    
        public virtual departamento departamento { get; set; }
        public virtual ICollection<persona> personas { get; set; }
        public virtual ICollection<sucursal> sucursals { get; set; }
    }
}
