//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW2PDT5
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona
    {
        public persona()
        {
            this.empleadoes = new HashSet<empleado>();
        }
    
        public int id_persona { get; set; }
        public string per_primer_nombre { get; set; }
        public string per_seg_nombre { get; set; }
        public string per_prim_apellido { get; set; }
        public string per_seg_apellido { get; set; }
        public string per_num_tel { get; set; }
        public string per_direcc { get; set; }
        public int MUNICIPIO_id_municipio { get; set; }
        public string numero_contribuyente { get; set; }
    
        public virtual ICollection<empleado> empleadoes { get; set; }
        public virtual municipio municipio { get; set; }
    }
}
