//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW2PDT5
{
    using System;
    using System.Collections.Generic;
    
    public partial class proveedor
    {
        public proveedor()
        {
            this.compra_proveedor = new HashSet<compra_proveedor>();
        }
    
        public int id_prov { get; set; }
        public string prov_nombre { get; set; }
        public string prov_direccion { get; set; }
        public string prov_tel { get; set; }
        public string prov_nit { get; set; }
        public string prov_iva { get; set; }
        public int TIPO_PROVEEDOR_id_tipo_prov { get; set; }
    
        public virtual ICollection<compra_proveedor> compra_proveedor { get; set; }
        public virtual tipo_proveedor tipo_proveedor { get; set; }
    }
}
