//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW2PDT5
{
    using System;
    using System.Collections.Generic;
    
    public partial class seccion_bodega
    {
        public seccion_bodega()
        {
            this.productoes = new HashSet<producto>();
        }
    
        public int id_seccion_bodega { get; set; }
        public string secc_bod_desc { get; set; }
    
        public virtual ICollection<producto> productoes { get; set; }
    }
}
