//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW2PDT5
{
    using System;
    using System.Collections.Generic;
    
    public partial class sucursal
    {
        public sucursal()
        {
            this.cajas = new HashSet<caja>();
            this.empleadoes = new HashSet<empleado>();
            this.producto_sucursal = new HashSet<producto_sucursal>();
        }
    
        public int id_sucursal { get; set; }
        public string suc_nombre { get; set; }
        public string suc_direccion { get; set; }
        public string suc_descripcion { get; set; }
        public string suc_telefono { get; set; }
        public int MUNICIPIO_id_municipio { get; set; }
    
        public virtual ICollection<caja> cajas { get; set; }
        public virtual ICollection<empleado> empleadoes { get; set; }
        public virtual municipio municipio { get; set; }
        public virtual ICollection<producto_sucursal> producto_sucursal { get; set; }
    }
}
