//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW2PDT5
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_proveedor
    {
        public tipo_proveedor()
        {
            this.proveedors = new HashSet<proveedor>();
        }
    
        public int id_tipo_prov { get; set; }
        public string tip_prov_desc { get; set; }
    
        public virtual ICollection<proveedor> proveedors { get; set; }
    }
}
