//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW2PDT5
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_venta
    {
        public tipo_venta()
        {
            this.ventas = new HashSet<venta>();
        }
    
        public int id_tipo_venta { get; set; }
    
        public virtual ICollection<venta> ventas { get; set; }
    }
}
