//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW2PDT5
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuario
    {
        public usuario()
        {
            this.compras = new HashSet<compra>();
            this.empleadoes = new HashSet<empleado>();
            this.venta_producto = new HashSet<venta_producto>();
            this.ventas = new HashSet<venta>();
        }
    
        public int id_usuario { get; set; }
        public string usu_nombre { get; set; }
        public string usu_contra { get; set; }
        public int ROL_id_rol { get; set; }
    
        public virtual ICollection<compra> compras { get; set; }
        public virtual ICollection<empleado> empleadoes { get; set; }
        public virtual rol rol { get; set; }
        public virtual ICollection<venta_producto> venta_producto { get; set; }
        public virtual ICollection<venta> ventas { get; set; }
    }
}
