//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISW2PDT5
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta_producto
    {
        public int id_vent_prod { get; set; }
        public int PRODUCTO_id_producto { get; set; }
        public int VENTA_id_venta { get; set; }
        public int USUARIO_id_usuario { get; set; }
    
        public virtual producto producto { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual venta venta { get; set; }
    }
}
